name: finamoonproject
description: Finance Manager on flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flutter_neumorphic: ^3.0.1
  cupertino_icons: ^0.1.3
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - locales/EN_US.json
    - locales/RU.json
