name: finamoonproject
description: Finance Manager on flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^0.6.3+4
  flutter_screen_lock: ^1.2.4
  flutter_cupertino_localizations: ^1.0.1
  flutter_neumorphic: ^3.0.1
  cupertino_icons: ^0.1.3
  http: ^0.12.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  select_dialog: ^1.2.1
  flutter_dialogflow: ^0.1.3
  bloc: ^6.1.0
  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  shared_preferences: ^0.5.1+2
  font_awesome_flutter: ^8.5.0
  intl: ^0.16.0
  flutter_screenutil: ^0.5.2
  flutter_colorpicker: ^0.2.6
  get_it: ^1.0.3+2
  sqflite: ^1.1.7+3
  path_provider: ^1.6.7
  provider: ^4.3.2+3
  dio: 2.0.22
  datetime_picker_formfield: ^1.0.0
  toast: ^0.1.5
  flutter_slidable: ^0.5.4
  jiffy: ^2.1.2
  sweetalert: ^0.0.1
  month_picker_dialog: ^0.3.1
  pie_chart: ^3.1.1
  responsive_grid: ^1.1.1
  custom_switch: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1

flutter:
  uses-material-design: true
  assets:
    - locales/EN_US.json
    - locales/RU.json
    - assets/FinaMoon-7e886f3862f3.json
