var constCategories = [
  ["Income", "Salary"],
  ["Income", "Rental"],
  ["Income", "Dividend"],
  ["Income", "Commission"],
  ["Income", "Bonus"],
  ["Expense", "Bills"],
  ["Expense", "Book"],
  ["Expense", "Children"],
  ["Expense", "Clothes"],
  ["Expense", "Entertainment"],
  ["Expense", "Food"],
  ["Expense", "Gifts"],
  ["Expense", "Groceries"],
  ["Expense", "Health"],
  ["Expense", "Others"],
  ["Expense", "Rent"],
  ["Expense", "Repair"],
  ["Expense", "Social"],
  ["Expense", "Sport"],
  ["Expense", "Subscription"],
  ["Expense", "Transport"],
  ["Expense", "Travel"],
  ["Expense", "Utilities"],
  ["Saving", "Emergency fund"],
  ["Saving","Investing fund"],
  ["Saving","Home fund"],
  ["Saving","College savings"],
  ["Saving","Fun savings"],
  ["Saving","Gift savings"],
];